version: '3.3'

services:
  desafio_luiza_labs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_PATH: "/${COMPOSE_PROJECT_NAME}"
        RAILS_PORT: ${RAILS_PORT}
    stdin_open: true
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:setup
        bundle exec rake db:migrate
        bundle exec rails s -p ${RAILS_PORT} -b ${RAILS_BIND}      
    env_file:
      - .env
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    volumes:
      - "./:/${COMPOSE_PROJECT_NAME}"
      - gems:/.gems
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:5.0.7

  postgres:
    image: postgres:12.1
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  gems:
  pgdata: